hmcts/ccd-docker

- README.md
- ccd
- compose/dm-store.yml
- database/init-db.sh
RDM-2828
Introduced an optional document management store in a separate dm-store.yml file.
run with: ./ccd enable backend frontend dm-store
```
[ ] Yes
[ X] No
```
> Added document0management-store-app as an optional docker compose file

- README.md
- bin/document-management-store-get.sh
- bin/document-management-store-migrate.sh
- ccd
- compose/dm-store.yml
https://tools.hmcts.net/jira/browse/RDM-3033
Configured azurite container and dm-store to use it.
```
[ ] Yes
[X ] No
```
> [PREVIEW] RDM-3033 Add Azurite - an emulator for Azure Blob Store

- ccd
Checkout as little as possible to try speedup the build
```
[ ] Yes
[x] No
```
> ccd: perform shallow clone

- compose/frontend.yml
Logout fix.
```
[ ] Yes
[X ] No
```
> Logout endpoint fix.

- README.md
- ccd
- compose/backend.yml
- compose/frontend.yml
https://tools.hmcts.net/jira/browse/RDM-3858
```
[ ] Yes
[ ] No
```
> Drop Artifactory

- README.md
RDM-3892
Update Prerequisites section to mention Azure CLI
```
[ ] Yes
[x] No
```
> RDM-3892 Update Prerequisites section to mention Azure CLI

- compose/backend.yml
add print service to docker env var for data-store so we can connect to a local instance of print service
```
[ ] Yes
[X] No
```
> Add print service auth

- README.md
> Add Azure Authentication steps for pulling images

- ccd
- compose/backend.yml
- compose/def-designer.yml
- compose/dm-store.yml
- compose/frontend.yml
https://tools.hmcts.net/jira/browse/RDM-4746
```
[ ] Yes
[ ] No
```
> Use AzureCR for our Docker images

- ccd
> RDM-5081-Updated ccd-api-gateway docker image name to web

- compose/dm-store.yml
https://tools.hmcts.net/jira/browse/RDM-5169
Set default storage to blob store for local docker instance
```
[ ] Yes
[x] No
```
> RDM-5169 - set default doc storage to blob store

- README.md
- bin/idam-create-caseworker.sh
https://tools.hmcts.net/jira/browse/RDM-5381
Simple tweak in README.
```
[ ] Yes
[X] No
```
> updated README for weak password precaution

- ccd
- compose/backend.yml
- compose/frontend.yml
https://tools.hmcts.net/jira/browse/RDM-5330
```
[ ] Yes
[ x] No
```
> RDM-5330-update ccd to use new docker registry url

- ccd
Fixed docker branch builds to inline hmctspublic.
```
[ ] Yes
[ x] No
```
> Fixed docker branch builds

- README.md
https://tools.hmcts.net/jira/browse/RDM-5429
Readme update for grey screen issues at login
```
[ ] Yes
[X] No
```
> added info for the grey screen issues

- README.md
- compose/backend.yml
- compose/frontend.yml
> reduced SIDAM mem and updated readme

- ccd
It's a public repo, shouldn't be logging in to it
> Force logout of hmctspublic

- ccd
- compose/backend.yml
- compose/frontend.yml
> RDM-5544- ACR references changes to hmctspublic and hmctsprivate

- compose/def-designer.yml
> RDM-5607- image reference changed to hmctspublic

- compose/backend.yml
- compose/others.yml
https://tools.hmcts.net/jira/browse/RDM-5722
Enable the AM-Db image in CCD-docker.
```
[ ] Yes
[x] No
```
> RDM-5722: Enable the AM-DB image from hmctspublic.

- compose/backend.yml
- compose/def-designer.yml
- compose/dm-store.yml
Removed links between services.
```
[ ] Yes
[x ] No
```
> RDM-6833-removed links between services- redundant

- compose/backend.yml
- compose/def-designer.yml
- compose/dm-store.yml
> Revert "RDM-6833-removed links between services- redundant"

- compose/backend.yml
https://tools.hmcts.net/jira/browse/RDM-7693
Issue with postgres image, to resolve this issue need to set below environment variable.
POSTGRES_HOST_AUTH_METHOD: trust
```
[ ] Yes
[ X] No
```
> RDM-7693: ccd-docker issue with ccd-shared-database postgres image

- compose/frontend.yml
N/A
Add the proxy payments environment variable to the ccd gateway config.
New to this docker stuff so let me know if I missed anything.
```
[ ] Yes
[x] No
```
> Expose proxy_payments gateway variable

- README.md
- ccd
- compose/manage-case-assignment.yml
https://tools.hmcts.net/jira/browse/RDM-8389
Update CCD docker for new micro-service
```
[ ] Yes
[ x] No
```
> RDM-8389 - docker compose for new micro-service "manage-case-assignment"

- bulk-user-setup/README.md
- bulk-user-setup/bulk-user-creation.sh
- bulk-user-setup/sample_test.csv
[RDM-8298](https://tools.hmcts.net/jira/browse/RDM-8298) _Bulk User Creation Script_
A script to perform IDAM user registrations in bulk from a CSV file.
```
[ ] Yes
[x] No
```
> RDM-8298 Bulk User Creation Script

- README.md
- bin/create-initial-roles-and-users.sh
https://tools.hmcts.net/jira/browse/RDM-8667
Introduce role(s) and user(s) needed for FTA of Organisation and OrganisationPolicy types
```
[ ] Yes
[X] No
```
> introduce caseworker-caa role and a user with that role

- README.md
> improved readme for IDAM stub

- compose/frontend.yml
> RDM-9262 - Add new ADMINWEB_ELASTIC_INDEX_URL env var

- bin/ccd-import-definition.sh
- bin/utils/idam-user-token.sh
- bin/utils/lease-service-token.sh
Not related to a specific JIRA ticket, but issues found whilst testing ACA-68
Make the output from selected ccd docker scripts easier to consume - easier to read, and simplify copying and pasting of values output by the scripts.
```
[ ] Yes
[X] No
```
> Update scripts to improve output

- compose/elasticsearch.yml
> Use hmctspublic for logstash

- compose/dm-store.yml
https://tools.hmcts.net/jira/browse/RDM-10357
White list xui_webapp in dm-store yml file
```
[ ] Yes
[ X] No
```
> RDM-10357: Whitelist xui_webapp in dm-store

- README.md
- ccd
- compose/message-publisher.yml
https://tools.hmcts.net/jira/browse/RDM-10417
Add CCD Message Publisher application to ccd-docker
```
[ ] Yes
[x] No
```
> RDM-10417 - Add ccd-message-publisher

- bin/add-idam-clients.sh
> Add in missing CCD admin client

- README.md
- compose/xui-frontend.yml
> Correct XUI instructions; add new env vars

- compose/case-document-am.yml
> case-doc-am env cleanup

- compose/backend.yml
RDM-12438: Add all access-control properties to CCD docker
[RDM-12438] (https://tools.hmcts.net/jira/browse/RDM-12438).
> RDM-12438: Add all access-control properties to CCD docker

- bulk-user-setup/bulk-user-update-CCD-1239.sh
Bespoke script for CCD-1239 to add caseworker-civil and caseworker-civil-solicitor roles
```
[x] Yes
[ ] No
```
> CCD-1239 Added bespoke script for CCD-1239

- compose/logstash.yml
Update for the logstash docker image. 
```
[ ] Yes
[ X] No
```
> Update logstash docker image for a working one.

- compose/backend.yml
Add URL to datastore to point to case-document-am-api docker image
```
[ ] Yes
[X] No
```
> Add URL to datastore to point to `case-document-am-api` docker image

- README.md
N/A
Update the readme to reflect the actual steps taken during onboarding.
```
[ ] Yes
[x] No
```
> NOJIRA Update the readme

- bin/add-role-assignments.sh
- database-v11/init-db.sh
> Updates for postgres v11

- bin/add-idam-clients.sh
- bin/users.json
- compose/backend.yml
https://tools.hmcts.net/jira/browse/RDM-12424
New client for data-store with the manage-user scope. New data store system user data.store.idam.system.user@gmail.com
```
[ ] Yes
[ X] No
```
> RDM-12424 New data store IDAM client and user

- compose/backend.yml
> CCD-1662 - Update Data Store env vars

- compose/logstash.yml
Set correct tags for service specific ccd/logstash images
```
[ ] Yes
[x] No
```
> Fix ccd/logstash image tags

- compose/backend.yml
[RDM-10924](https://tools.hmcts.net/jira/browse/RDM-10924) _"Migrate Grant Access to a Case APIs to new Access Control"_
Adjust config used by `am-role-assignment-service`:
* change IDAM client scope to match `/bin/add-idam-clients.sh`
* change micro-service name in `service-auth-provider-api` settings.
```
[ ] Yes
[x] No
```
> RDM-10924: adjust role-assignment-service settings

- compose/frontend.yml
> Align Admin Web IDAM client secret value

- compose/backend.yml
https://tools.hmcts.net/jira/browse/ACA-142
New ACA API: Get Case assigned users and roles
```
[ ] Yes
[X] No
```
> ACA-142 Add authorisation for AAC repo

- compose/dm-store.yml
https://github.com/hmcts/ccd-data-store-api/pull/1669
Needed to test RDM-12862 locally on docker stack
```
[ ] Yes
[X] No
```
> RDM-12862  - Add `ccd_data` to service to service whitelist

- README.md
- ccd
- compose/dm-store.yml
- compose/frontend.yml
> Ccd 2331 remove CCD UI

- bin/env_variables_all.txt
[RDM-13120](https://tools.hmcts.net/jira/browse/RDM-13120) _"Reinstate RefData location lookup checks in GlobalSearch endpoint FTAs"_
[RDM-13121](https://tools.hmcts.net/jira/browse/RDM-13121) _"Add RefData service lookup checks to GlobalSearch endpoint FTAs"_
Add hostname for RefData location API for use in GS RefData FTAs.
```
[ ] Yes
[x] No
```
> RDM-13120 and RDM-13121 GS RefData FTA lookups

- compose/elasticsearch.yml
> Update ES to v7

- bin/ccd-roles.json
- bin/users.json
> WLTS-11 add new roles

- bulk-user-setup/README.md
- bulk-user-setup/bulk-user-creation-and-update.sh
https://tools.hmcts.net/jira/browse/CCD-3350
bulk-user-creation.sh - Added comment to remove port issues (Due to old IDAM shutdown)
bulk-user-creation-and-update.sh - The full script
README.md - Spelling mistake in first linealso updated the formatting as some fields are only mandatory for some scripts
```
[ ] Yes
[ X] No
```
> CCD-3350 , ProxyShutdown & Spelling Mistake

- compose/frontend.yml
> Add missing `ADMINWEB_GET_DICTIONARY_URL` for Admin Web 

- README.md
Updating README for troubleshooting on Apple Silicon (ARM64)
Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```
> Added section for troubleshooting apple silicon

- README.md
https://tools.hmcts.net/jira/browse/CCD-5568
Updated README for Apple Silicon to reflect new settings defaults
```
[ ] Yes
[x ] No
```
> Updated README for Apple Silicon to reflect new settings defaults

- bulk-user-setup/bulk-user-setup.config
- bulk-user-setup/bulk-user-setup.sh
Functionality added as part of -> Incident INC5640676
functionality to allow amending  an inactive user account
```
[ ] Yes
[X] No
```
> INC5640676 -> functionality to allow amending  an inactive user account

- bulk-user-setup/bulk-user-setup.config
- bulk-user-setup/bulk-user-setup.sh
NA
Amend existing user given idam id to add remove idam roles.
```
[ ] Yes
[X] No
```
> Amend user roles by idam & allow processing inactive user

- bulk-user-setup/bulk-user-setup.config
- bulk-user-setup/bulk-user-setup.sh
NA
Patch :: Addition of new command 'deleteuser'
```
[ ] Yes
[X] No
```
> Patch :: Addition of new command 'deleteuser'
